name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Cache TypeScript build info
        uses: actions/cache@v4
        with:
          path: |
            tsconfig.tsbuildinfo
            .tsc-cache
          key: ${{ runner.os }}-tsc-${{ hashFiles('**/tsconfig.json', 'src/**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-tsc-

      - name: Run TypeScript type check
        run: npm run typecheck

      - name: Cache ESLint
        uses: actions/cache@v4
        with:
          path: .eslintcache
          key: ${{ runner.os }}-eslint-${{ hashFiles('**/eslint.config.ts', 'src/**/*.ts') }}
          restore-keys: |
            ${{ runner.os }}-eslint-

      - name: Run ESLint
        run: npm run lint

      - name: Check code formatting
        run: npm run format:check

      - name: Cache Vitest
        uses: actions/cache@v4
        with:
          path: |
            .vitest-cache
            node_modules/.vite
          key: ${{ runner.os }}-vitest-${{ hashFiles('**/vitest.config.ts', 'src/**/*.test.ts') }}
          restore-keys: |
            ${{ runner.os }}-vitest-

      - name: Run tests
        run: npm test
