name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: macos-latest
            arch: x64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x64
          - os: ubuntu-latest
            arch: x64

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev

    - name: Install dependencies
      run: npm ci

    - name: Type check
      run: npm run typecheck

    - name: Build Electron app
      run: npm run dist -- --${{ matrix.arch }} --publish never
      env:
        ELECTRON_BUILDER_ALLOW_UNRESOLVED_DEPENDENCIES: true

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.os }}-${{ matrix.arch }}-build
        path: |
          dist/*
          !dist/builder-debug.yml

  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch all history for changelog generation

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Linux dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y libx11-dev libxtst-dev libxt-dev libx11-xcb-dev libxkbcommon-dev libxkbcommon-x11-dev

    - name: Install dependencies
      run: npm ci

    - name: Generate changelog
      run: npm run changelog

    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Remove builder-debug.yml files
      run: |
        find . -name "builder-debug.yml" -type f -delete

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          macos-latest-x64-build/*
          macos-latest-arm64-build/*
          windows-latest-x64-build/*
          ubuntu-latest-x64-build/*
        draft: false
        prerelease: false
        fail_on_unmatched_files: false
        body_path: RELEASE_NOTES.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
